"""init: create users, rooms, messages tables"""



# revision identifiers, used by Alembic.
revision = 'fb5248b812d3'
down_revision = '081da0c62e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

